////// GRAPHIC GLOBALS
int screenH = 768;
int screenW = 1024;
int screenHeight = 695;
int screenWidth = 790; 
int cameraX = 0;
int cameraY = 0;
int TownID = 0;
time_t rawtime;
FONT* font1=NULL;
FONT* MenuFont=NULL;
BITMAP* buffer=NULL;
BITMAP* loader=NULL;
BITMAP* help=NULL;
BITMAP* help1=NULL;
BITMAP* help2=NULL;
BITMAP* background=NULL;
BITMAP* MenuBackground=NULL;
BITMAP* player_right=NULL;
BITMAP* player_right1=NULL;
BITMAP* player_right2=NULL;
BITMAP* player_right3=NULL;
BITMAP* player_right4=NULL;
BITMAP* player_right5=NULL;
BITMAP* player_right6=NULL;
BITMAP* player_right7=NULL;
BITMAP* player_right8=NULL;
BITMAP* player_left=NULL;
BITMAP* player_left1=NULL;
BITMAP* player_left2=NULL;
BITMAP* player_left3=NULL;
BITMAP* player_left4=NULL;
BITMAP* player_left5=NULL;
BITMAP* player_left6=NULL;
BITMAP* player_left7=NULL;
BITMAP* player_left8=NULL;
BITMAP* player_up=NULL;
BITMAP* player_up1=NULL;
BITMAP* player_up2=NULL;
BITMAP* player_up3=NULL;
BITMAP* player_up4=NULL;
BITMAP* player_up5=NULL;
BITMAP* player_up6=NULL;
BITMAP* player_up7=NULL;
BITMAP* player_up8=NULL;
BITMAP* player_down=NULL;
BITMAP* player_down1=NULL;
BITMAP* player_down2=NULL;
BITMAP* player_down3=NULL;
BITMAP* player_down4=NULL;
BITMAP* player_down5=NULL;
BITMAP* player_down6=NULL;
BITMAP* player_down7=NULL;
BITMAP* player_down8=NULL;
BITMAP* no_tile=NULL;
BITMAP* grass=NULL;
BITMAP* dirt=NULL;
BITMAP* cobblestone=NULL;
BITMAP* water1=NULL;
BITMAP* water2=NULL;
BITMAP* water3=NULL;
BITMAP* water4=NULL;
BITMAP* waterbank_up=NULL;
BITMAP* waterbank_down=NULL;
BITMAP* waterbank_left=NULL;
BITMAP* waterbank_right=NULL;
BITMAP* waterbank_ulcorner=NULL;
BITMAP* waterbank_urcorner=NULL;
BITMAP* waterbank_drcorner=NULL;
BITMAP* waterbank_dlcorner=NULL;
BITMAP* waterfall0=NULL;
BITMAP* waterfall1=NULL;
BITMAP* waterfall2=NULL;
BITMAP* waterfall3=NULL;
BITMAP* waterfall4=NULL;
BITMAP* waterfall5=NULL;
BITMAP* waterfall6=NULL;
BITMAP* waterfall7=NULL;
BITMAP* waterfall8=NULL;
BITMAP* waterfall9=NULL;
BITMAP* trees=NULL;
BITMAP* tree2=NULL;
BITMAP* tree_big=NULL;
BITMAP* mount=NULL;
BITMAP* camp1=NULL;
BITMAP* camp2=NULL;
BITMAP* camp3=NULL;
BITMAP* camp4=NULL;
BITMAP* camp5=NULL;
BITMAP* camp6=NULL;
BITMAP* camp7=NULL;
BITMAP* camp8=NULL;
BITMAP* camping=NULL;
BITMAP* cave=NULL;
BITMAP* house=NULL;
BITMAP* house_forest=NULL;
BITMAP* house_forest2=NULL;
BITMAP* house_stone=NULL;
BITMAP* castle=NULL;
BITMAP* castle2=NULL;
BITMAP* builder=NULL;
BITMAP* tavern_human=NULL;
BITMAP* tavern_dwarven=NULL;
BITMAP* tavern_elven=NULL;
BITMAP* unit_pikemen=NULL;
BITMAP* unit_archers=NULL;
BITMAP* unit_scouts=NULL;
BITMAP* unit_mages=NULL;
BITMAP* unit_warriors=NULL;
BITMAP* unit_priests=NULL;
BITMAP* gold=NULL;
BITMAP* wood=NULL;
BITMAP* ore=NULL;
BITMAP* book=NULL;
BITMAP* Level=NULL;
BITMAP* death=NULL;
BITMAP* fight=NULL;
BITMAP* treescreen=NULL;
BITMAP* foresthousescreen=NULL;
BITMAP* cavescreen=NULL;
BITMAP* wingame;

void init() 
{
    cout<<"Installing Allegro graphics...";
	int depth, res;
	allegro_init();
	depth = desktop_color_depth();
	if (depth == 0) depth = 32;
	set_color_depth(depth);
	res = set_gfx_mode(GFX_AUTODETECT_WINDOWED, screenW, screenH, 0, 0);
	if (res != 0) 
    {
		allegro_message(allegro_error);
		exit(-1);
	}

	install_timer();
	install_int_ex( increment_speed, BPS_TO_TIMER( 80 ) );
	install_keyboard();
	install_mouse();
	install_sound( DIGI_AUTODETECT, MIDI_AUTODETECT, "A" );
    set_volume( 127, 127 );
	cout<<"Done"<<endl;
}

void deinit() 
{
	clear_keybuf();
	destroy_bitmap(buffer);
	destroy_bitmap(loader);
	destroy_bitmap(help);
	destroy_bitmap(help1);
	destroy_bitmap(help2);
	destroy_bitmap(background);
	destroy_bitmap(MenuBackground);
	destroy_bitmap(player_right);
	destroy_bitmap(player_right1);
	destroy_bitmap(player_right2);
	destroy_bitmap(player_right3);
	destroy_bitmap(player_right4);
	destroy_bitmap(player_right5);
	destroy_bitmap(player_right6);
	destroy_bitmap(player_right7);
	destroy_bitmap(player_right8);
	destroy_bitmap(player_left);
	destroy_bitmap(player_left1);
	destroy_bitmap(player_left2);
	destroy_bitmap(player_left3);
	destroy_bitmap(player_left4);
	destroy_bitmap(player_left5);
	destroy_bitmap(player_left6);
	destroy_bitmap(player_left7);
	destroy_bitmap(player_left8);
	destroy_bitmap(player_up);
	destroy_bitmap(player_up1);
	destroy_bitmap(player_up2);
	destroy_bitmap(player_up3);
	destroy_bitmap(player_up4);
	destroy_bitmap(player_up5);
	destroy_bitmap(player_up6);
	destroy_bitmap(player_up7);
	destroy_bitmap(player_up8);
	destroy_bitmap(player_down);
	destroy_bitmap(player_down1);
	destroy_bitmap(player_down2);
	destroy_bitmap(player_down3);
	destroy_bitmap(player_down4);
	destroy_bitmap(player_down5);
	destroy_bitmap(player_down6);
	destroy_bitmap(player_down7);
	destroy_bitmap(player_down8);
	destroy_bitmap(no_tile);
	destroy_bitmap(grass);
	destroy_bitmap(dirt);
	destroy_bitmap(cobblestone);
	destroy_bitmap(water1);
	destroy_bitmap(water2);
	destroy_bitmap(water3);
	destroy_bitmap(water4);
	destroy_bitmap(waterbank_up);
	destroy_bitmap(waterbank_down);
	destroy_bitmap(waterbank_left);
	destroy_bitmap(waterbank_right);
	destroy_bitmap(waterbank_ulcorner);
	destroy_bitmap(waterbank_urcorner);
	destroy_bitmap(waterbank_dlcorner);
	destroy_bitmap(waterbank_drcorner);
	destroy_bitmap(waterfall0);
	destroy_bitmap(waterfall1);
	destroy_bitmap(waterfall2);
	destroy_bitmap(waterfall3);
	destroy_bitmap(waterfall4);
	destroy_bitmap(waterfall5);
	destroy_bitmap(waterfall6);
	destroy_bitmap(waterfall7);
	destroy_bitmap(waterfall8);
	destroy_bitmap(waterfall9);
	destroy_bitmap(trees);
	destroy_bitmap(tree2);
	destroy_bitmap(tree_big);
	destroy_bitmap(mount);
	destroy_bitmap(camp1);
	destroy_bitmap(camp2);
	destroy_bitmap(camp3);
	destroy_bitmap(camp4);
	destroy_bitmap(camp5);
	destroy_bitmap(camp6);
	destroy_bitmap(camp7);
	destroy_bitmap(camp8);
	destroy_bitmap(camping);
	destroy_bitmap(cave);
	destroy_bitmap(house);
	destroy_bitmap(house_forest);
	destroy_bitmap(house_forest2);
	destroy_bitmap(house_stone);
	destroy_bitmap(castle);
	destroy_bitmap(castle2);
	destroy_bitmap(builder);
	destroy_bitmap(tavern_human);
	destroy_bitmap(tavern_dwarven);
	destroy_bitmap(tavern_elven);
	destroy_bitmap(unit_pikemen);
	destroy_bitmap(unit_archers);
	destroy_bitmap(unit_scouts);
	destroy_bitmap(unit_mages);
	destroy_bitmap(unit_warriors);
	destroy_bitmap(unit_priests);
	destroy_bitmap(gold);
	destroy_bitmap(wood);
	destroy_bitmap(ore);
	destroy_bitmap(book);
	destroy_bitmap(Level);
	destroy_bitmap(death);
	destroy_bitmap(fight);
	destroy_bitmap(treescreen);
	destroy_bitmap(foresthousescreen);
	destroy_bitmap(cavescreen);
	destroy_bitmap(wingame);
	destroy_font(font1);
	destroy_font(MenuFont);
    remove_int( increment_speed );
	/* add other deinitializations here */
}

BITMAP* LoadBMP(char* path, int* x)
{
        std::cout<<"Loading "<<path<<"...";
        BITMAP* temp;
        temp = load_bitmap(path, NULL);
        std::cout<<"Success"<<std::endl;
        return temp;
}

void LoadGraphics()
{
	background = LoadBMP("data\\graphics\\background.bmp", NULL);
	no_tile = LoadBMP("data\\graphics\\no_tile.bmp", NULL);
	grass = LoadBMP("data\\graphics\\grass.bmp", NULL);
	dirt = LoadBMP("data\\graphics\\dirt.bmp", NULL);
	cobblestone = LoadBMP("data\\graphics\\cobblestone.bmp", NULL);
	water1 = LoadBMP("data\\graphics\\water1.bmp", NULL);
	water2 = LoadBMP("data\\graphics\\water2.bmp", NULL);
	water3 = LoadBMP("data\\graphics\\water3.bmp", NULL);
	water4 = LoadBMP("data\\graphics\\water4.bmp", NULL);
	waterbank_up = LoadBMP("data\\graphics\\waterbank_up.bmp", NULL);
	waterbank_down = LoadBMP("data\\graphics\\waterbank_down.bmp", NULL);
	waterbank_right = LoadBMP("data\\graphics\\waterbank_right.bmp", NULL);
	waterbank_left = LoadBMP("data\\graphics\\waterbank_left.bmp", NULL);
	waterbank_ulcorner = LoadBMP("data\\graphics\\waterbank_ulcor.bmp", NULL);
	waterbank_urcorner = LoadBMP("data\\graphics\\waterbank_urcor.bmp", NULL);
	waterbank_drcorner = LoadBMP("data\\graphics\\waterbank_drcor.bmp", NULL);
	waterbank_dlcorner = LoadBMP("data\\graphics\\waterbank_dlcor.bmp", NULL);
	waterfall0 = LoadBMP("data\\graphics\\waterfall0.bmp", NULL);
	waterfall1 = LoadBMP("data\\graphics\\waterfall1.bmp", NULL);
	waterfall2 = LoadBMP("data\\graphics\\waterfall2.bmp", NULL);
	waterfall3 = LoadBMP("data\\graphics\\waterfall3.bmp", NULL);
	waterfall4 = LoadBMP("data\\graphics\\waterfall4.bmp", NULL);
	waterfall5 = LoadBMP("data\\graphics\\waterfall5.bmp", NULL);
	waterfall6 = LoadBMP("data\\graphics\\waterfall6.bmp", NULL);
	waterfall7 = LoadBMP("data\\graphics\\waterfall7.bmp", NULL);
	waterfall8 = LoadBMP("data\\graphics\\waterfall8.bmp", NULL);
	waterfall9 = LoadBMP("data\\graphics\\waterfall9.bmp", NULL);
    trees = LoadBMP("data\\graphics\\trees.bmp", NULL);
	tree2 = LoadBMP("data\\graphics\\tree2.bmp", NULL);
	tree_big = LoadBMP("data\\graphics\\tree_big.bmp", NULL);
	mount = LoadBMP("data\\graphics\\mount.bmp", NULL);
	cave = LoadBMP("data\\graphics\\cave.bmp", NULL);
	camp1 = LoadBMP("data\\graphics\\camp1.bmp", NULL);
	camp2 = LoadBMP("data\\graphics\\camp2.bmp", NULL);
	camp3 = LoadBMP("data\\graphics\\camp3.bmp", NULL);
	camp4 = LoadBMP("data\\graphics\\camp4.bmp", NULL);
	camp5 = LoadBMP("data\\graphics\\camp5.bmp", NULL);
	camp6 = LoadBMP("data\\graphics\\camp6.bmp", NULL);
	camp7 = LoadBMP("data\\graphics\\camp7.bmp", NULL);
	camp8 = LoadBMP("data\\graphics\\camp8.bmp", NULL);
	camping = LoadBMP("data\\graphics\\alphacoders_306183.bmp", NULL);
	house = LoadBMP("data\\graphics\\house.bmp", NULL);
	castle = LoadBMP("data\\graphics\\castle.bmp", NULL);
	castle2 = LoadBMP("data\\graphics\\castle2.bmp", NULL);
	house_forest = LoadBMP("data\\graphics\\house_forest.bmp", NULL);
	house_forest2 = LoadBMP("data\\graphics\\house_forest2.bmp", NULL);
	house_stone = LoadBMP("data\\graphics\\house_stone.bmp", NULL);
	player_right = LoadBMP("data\\graphics\\player_right.bmp", NULL);
	player_right1 = LoadBMP("data\\graphics\\player_right1.bmp", NULL);
	player_right2 = LoadBMP("data\\graphics\\player_right2.bmp", NULL);
	player_right3 = LoadBMP("data\\graphics\\player_right3.bmp", NULL);
	player_right4 = LoadBMP("data\\graphics\\player_right4.bmp", NULL);
	player_right5 = LoadBMP("data\\graphics\\player_right5.bmp", NULL);
	player_right6 = LoadBMP("data\\graphics\\player_right6.bmp", NULL);
	player_right7 = LoadBMP("data\\graphics\\player_right7.bmp", NULL);
	player_right8 = LoadBMP("data\\graphics\\player_right8.bmp", NULL);
	player_left = LoadBMP("data\\graphics\\player_left.bmp", NULL);
	player_left1 = LoadBMP("data\\graphics\\player_left1.bmp", NULL);
	player_left2 = LoadBMP("data\\graphics\\player_left2.bmp", NULL);
	player_left3 = LoadBMP("data\\graphics\\player_left3.bmp", NULL);
	player_left4 = LoadBMP("data\\graphics\\player_left4.bmp", NULL);
	player_left5 = LoadBMP("data\\graphics\\player_left5.bmp", NULL);
	player_left6 = LoadBMP("data\\graphics\\player_left6.bmp", NULL);
	player_left7 = LoadBMP("data\\graphics\\player_left7.bmp", NULL);
	player_left8 = LoadBMP("data\\graphics\\player_left8.bmp", NULL);
	player_up = LoadBMP("data\\graphics\\player_up.bmp", NULL);
	player_up1 = LoadBMP("data\\graphics\\player_up1.bmp", NULL);
	player_up2 = LoadBMP("data\\graphics\\player_up2.bmp", NULL);
	player_up3 = LoadBMP("data\\graphics\\player_up3.bmp", NULL);
	player_up4 = LoadBMP("data\\graphics\\player_up4.bmp", NULL);
	player_up5 = LoadBMP("data\\graphics\\player_up5.bmp", NULL);
	player_up6 = LoadBMP("data\\graphics\\player_up6.bmp", NULL);
	player_up7 = LoadBMP("data\\graphics\\player_up7.bmp", NULL);
	player_up8 = LoadBMP("data\\graphics\\player_up8.bmp", NULL);
	player_down = LoadBMP("data\\graphics\\player_down.bmp", NULL);
	player_down1 = LoadBMP("data\\graphics\\player_down1.bmp", NULL);
	player_down2 = LoadBMP("data\\graphics\\player_down2.bmp", NULL);
	player_down3 = LoadBMP("data\\graphics\\player_down3.bmp", NULL);
	player_down4 = LoadBMP("data\\graphics\\player_down4.bmp", NULL);
	player_down5 = LoadBMP("data\\graphics\\player_down5.bmp", NULL);
	player_down6 = LoadBMP("data\\graphics\\player_down6.bmp", NULL);
	player_down7 = LoadBMP("data\\graphics\\player_down7.bmp", NULL);
	player_down8 = LoadBMP("data\\graphics\\player_down8.bmp", NULL);
	builder = LoadBMP("data\\towns\\builder.bmp", NULL);
	tavern_human = LoadBMP("data\\graphics\\tavern_human.bmp", NULL);
	tavern_dwarven = LoadBMP("data\\graphics\\tavern_dwarven.bmp", NULL);
	tavern_elven = LoadBMP("data\\graphics\\tavern_elven.bmp", NULL);
	unit_pikemen = LoadBMP("data\\graphics\\Unit_Pikeman.bmp", NULL);
	unit_archers = LoadBMP("data\\graphics\\Unit_Archer.bmp", NULL);
	unit_scouts = LoadBMP("data\\graphics\\Unit_Scout.bmp", NULL);
	unit_mages = LoadBMP("data\\graphics\\Unit_Mage.bmp", NULL);
	unit_warriors = LoadBMP("data\\graphics\\Unit_Warrior.bmp", NULL);
	unit_priests = LoadBMP("data\\graphics\\Unit_Priest.bmp", NULL);
	gold = LoadBMP("data\\graphics\\gold.bmp", NULL);
	wood = LoadBMP("data\\graphics\\wood.bmp", NULL);
	ore = LoadBMP("data\\graphics\\ore.bmp", NULL);
	book = LoadBMP("data\\graphics\\book.bmp", NULL);
	Level = LoadBMP("data\\graphics\\level.bmp", NULL);
	death = LoadBMP("data\\graphics\\alphacoders_291386.bmp", NULL);
	fight = LoadBMP("data\\graphics\\alphacoders_204687.bmp", NULL);
	treescreen = LoadBMP("data\\graphics\\alphacoders_110624.bmp", NULL);
	foresthousescreen = LoadBMP("data\\graphics\\alphacoders_225665.bmp", NULL);
	cavescreen = LoadBMP("data\\graphics\\alphacoders_202486.bmp", NULL);
	wingame = LoadBMP("data\\graphics\\Kerembeyit_Shout.bmp", NULL);
}
